version: 0.2
phases: 
  pre_build: 
    commands: 
    - echo Logging in to Amazon ECR.... 
    - aws --version
    - $(aws ecr get-login --region us-east-1 --no-include-email)
    # Get commit hash value to tag the image
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
    # Replace with your application name
    - APPLICATION_NAME=api-service
    # Replace with this 435320931996.dkr.ecr.ap-south-1.amazonaws.com to your repository URI
    - REPOSITORY_URI=708612503855.dkr.ecr.us-east-1.amazonaws.com/$APPLICATION_NAME
  build: 
    commands: 
    - echo Build started on `date` 
    - echo Building the Docker image... 
    - docker build -t $APPLICATION_NAME:$IMAGE_TAG .
    - docker tag $APPLICATION_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG 
  post_build: 
    commands: 
    - echo Build completed on `date` 
    - echo pushing to repo
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing image definitions file... 
    # Give your container name
    - printf '[{"name":"ApiServiceContainer", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json